

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Statement;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Alain
 */
public class Menu extends javax.swing.JFrame {
    Conectar con = new Conectar();
    Connection conet;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    int idc;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        jLabel2.setBackground(Color.black);
//        UIManager Ui = new UIManager();
//        Ui.put("nimbusBlueGrey", new ColorUIResource(103, 0, 3));
//       jTableEspeccialidad.getTableHeader().setForeground(Color.white);
//        jTableAnimales.getTableHeader().setForeground(Color.white);
    }

    public void cambiarPanel(JPanel jPanel) {

        jPanel.setSize(500, 550);
        jPanel.setLocation(0, 0);

        jPaneltablaPrincipal.removeAll();
        jPaneltablaPrincipal.add(jPanel, BorderLayout.CENTER);
        jPaneltablaPrincipal.revalidate();
        jPaneltablaPrincipal.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAnimales = new javax.swing.JButton();
        jButtonCuidados = new javax.swing.JButton();
        jButtonEspecialidad = new javax.swing.JButton();
        jButtonCuidadores = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPaneltablaPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAnimales.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAnimales.setText("Animales");
        jButtonAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnimalesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 70));

        jButtonCuidados.setBackground(new java.awt.Color(153, 153, 153));
        jButtonCuidados.setText("Cuidados");
        jButtonCuidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuidadosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCuidados, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 170, 70));

        jButtonEspecialidad.setBackground(new java.awt.Color(153, 153, 153));
        jButtonEspecialidad.setText("Especialidad");
        jButtonEspecialidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspecialidadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 170, 70));

        jButtonCuidadores.setBackground(new java.awt.Color(153, 153, 153));
        jButtonCuidadores.setText("Cuidadores");
        jButtonCuidadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuidadoresActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCuidadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 170, 70));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setText("Usuario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 170, 70));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Vladimir Script", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tropical-jungle-1.jpeg"))); // NOI18N
        jLabel1.setText("vvv");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 560));

        javax.swing.GroupLayout jPaneltablaPrincipalLayout = new javax.swing.GroupLayout(jPaneltablaPrincipal);
        jPaneltablaPrincipal.setLayout(jPaneltablaPrincipalLayout);
        jPaneltablaPrincipalLayout.setHorizontalGroup(
            jPaneltablaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPaneltablaPrincipalLayout.setVerticalGroup(
            jPaneltablaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPaneltablaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPaneltablaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnimalesActionPerformed
//        addAnimal a= new addAnimal();
//        a.setVisible(true);
//        this.setVisible(false);
        PanelTablaAnimal p = new PanelTablaAnimal();

        cambiarPanel(p);


    }//GEN-LAST:event_jButtonAnimalesActionPerformed

    private void jButtonCuidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuidadosActionPerformed
//        addCuidado c = new addCuidado();
//        c.setVisible(true);
//        this.setVisible(false);
        PanelCuidados p = new PanelCuidados();

        cambiarPanel(p);
    }//GEN-LAST:event_jButtonCuidadosActionPerformed

    private void jButtonEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspecialidadActionPerformed
//        addEspecialidad e = new addEspecialidad();
//        e.setVisible(true);
//        this.setVisible(false);
           PanelEspecialidad p = new PanelEspecialidad();

        cambiarPanel(p);
    }//GEN-LAST:event_jButtonEspecialidadActionPerformed

    private void jButtonCuidadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuidadoresActionPerformed
//        addCuidadores b=new addCuidadores();
//        b.setVisible(true);
//        this.setVisible(false);

        PanelCuidadores p = new PanelCuidadores();

        cambiarPanel(p);
    }//GEN-LAST:event_jButtonCuidadoresActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        PanelUsuarios u = new PanelUsuarios();
        
        cambiarPanel(u);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAnimales;
    private javax.swing.JButton jButtonCuidadores;
    private javax.swing.JButton jButtonCuidados;
    private javax.swing.JButton jButtonEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPaneltablaPrincipal;
    // End of variables declaration//GEN-END:variables
}
