
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Alain
 */
public class PanelTablaAnimal extends javax.swing.JPanel {

    Conectar con = new Conectar();
    Connection conet;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    int idc;

    /**
     * Creates new form PanelTablaAnimal
     */
    public PanelTablaAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnimal = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonIngresar = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAnimal.setBackground(new java.awt.Color(153, 153, 153));
        jTableAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Especie", "Raza", "Peso", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAnimalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAnimal);
        if (jTableAnimal.getColumnModel().getColumnCount() > 0) {
            jTableAnimal.getColumnModel().getColumn(0).setResizable(false);
            jTableAnimal.getColumnModel().getColumn(1).setResizable(false);
            jTableAnimal.getColumnModel().getColumn(2).setResizable(false);
            jTableAnimal.getColumnModel().getColumn(3).setResizable(false);
            jTableAnimal.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 519, 450));

        jButtonEditar.setText("Editar");
        jButtonEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonEditar.setIconTextGap(5);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 80, 30));

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonBorrar.setMaximumSize(new java.awt.Dimension(50, 20));
        jButtonBorrar.setMinimumSize(new java.awt.Dimension(50, 20));
        jButtonBorrar.setPreferredSize(new java.awt.Dimension(50, 20));
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 80, 30));

        jButtonIngresar.setText("Registrar");
        jButtonIngresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 80, 30));

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });
        add(jButtonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 80, 30));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Animales");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 380, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagen-de-archivo-de-gorilas-en-el-zoo-de-madrid.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Actualmente no esta en esta version");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        addAnimal a = new addAnimal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        consultar();
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jTableAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAnimalMouseClicked

    }//GEN-LAST:event_jTableAnimalMouseClicked

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        int fila = jTableAnimal.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se seleccionó fila");
        } else {
            idc = Integer.parseInt((String) jTableAnimal.getValueAt(fila, 0).toString());
            try {
                PreparedStatement elim = conet.prepareStatement("DELETE FROM animales WHERE id=' " + idc + "'");
                elim.executeUpdate();
                consultar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e + "No se logro borrar el registro");
            }

        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed
    private void consultar() {
        String sql = "SELECT * FROM animales";
        
        try {
            conet = con.getConexion();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] animal = new Object[5];

            model = (DefaultTableModel) jTableAnimal.getModel();
            while (rs.next()) {
                animal[0] = rs.getInt("id");
                animal[1] = rs.getString("especie");
                animal[2] = rs.getString("raza");
                animal[3] = rs.getFloat("peso");
                animal[4] = rs.getString("nombre");
                model.addRow(animal);
            }
            jTableAnimal.setModel(model);
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void limpiarTabla() {
        for (int i = 0; i <= jTableAnimal.getRowCount(); i++) {
            model.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAnimal;
    // End of variables declaration//GEN-END:variables
}
