
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Alain
 */
public class PanelCuidados extends javax.swing.JPanel {

    Conectar con = new Conectar();
    Connection conet;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    int idc;

    /**
     * Creates new form PanelCuidados
     */
    public PanelCuidados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuidados = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonIngresar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCuidados.setBackground(new java.awt.Color(153, 153, 153));
        jTableCuidados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Comida", "Cantidad comida", "Coste", "Habitat", "Animal", "Cuidador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCuidados);
        if (jTableCuidados.getColumnModel().getColumnCount() > 0) {
            jTableCuidados.getColumnModel().getColumn(0).setResizable(false);
            jTableCuidados.getColumnModel().getColumn(1).setResizable(false);
            jTableCuidados.getColumnModel().getColumn(2).setResizable(false);
            jTableCuidados.getColumnModel().getColumn(3).setResizable(false);
            jTableCuidados.getColumnModel().getColumn(4).setResizable(false);
            jTableCuidados.getColumnModel().getColumn(5).setResizable(false);
            jTableCuidados.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 510, 420));

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jButtonMostrar.setText("Mostrar");
        add(jButtonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cuidados");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 460, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EdE6XfsXoAMBuRi.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
         addCuidado c = new addCuidado();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Actualmente no esta en esta version");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
      int fila = jTableCuidados.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "No se seleccionó fila");
        }else{
            idc = Integer.parseInt((String) jTableCuidados.getValueAt(fila, 0).toString());
            try{
                PreparedStatement elim = conet.prepareStatement("DELETE FROM usuarios WHERE id=' "+idc+"'");
                elim.executeUpdate();
                consultar();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e + "No se logro borrar el registro");
            }
            
        }
        
    }//GEN-LAST:event_jButtonBorrarActionPerformed
private void consultar() {
        String sql = "SELECT * FROM cuidados";

        try {
            conet = con.getConexion();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] cuidados = new Object[7];

            model = (DefaultTableModel) jTableCuidados.getModel();
            while (rs.next()) {
                cuidados[0] = rs.getInt("id");
                cuidados[1] = rs.getString("Comida");
                cuidados[2] = rs.getString("Cantidad comida");
                cuidados[3] = rs.getFloat("coste");
                cuidados[4] = rs.getString("Habitat");
                cuidados[5] = rs.getInt("Animal");
                cuidados[6] = rs.getInt("Cuidador");
                model.addRow(cuidados);
            }
            jTableCuidados.setModel(model);
        } catch (SQLException e) {
        }
    }

    private void limpiarTabla() {
        for (int i = 0; i <= jTableCuidados.getRowCount(); i++) {
            model.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCuidados;
    // End of variables declaration//GEN-END:variables
}
